### ISSUE TITLE
formio-vue

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/vue-formio#1]
Dear @randallknutson,

I was extracting some of the code of my Vue app the uses Form.io to generate exactly this library.
I tried importing this one but sadly didn't work for me out of the box.

I was able to grab your code and create a full Vue component (Sorry that I copied everything that you had) and now its working as expected in the App.

Want to have a look at what I have?
[https://github.com/cabrerabywaters/formio-vue](url)
We also hope to release a full Vue hybrid app for data collection that connects to Form.io in the next couple weeks (We are still fixing some bugs and cleaning the code)

You can take a look at the dev page [http://fast.surge.sh/](url) for an example of an app built with this
The app includes full offline form submitting, multilanguage and automated deployment form Android (IOS on the way),Mac and PC using cordova 

Regards!

**Comment by randallknutson** [comment]
Its awesome that you built your own library! Ours should now be much improved and you should check it out again.
