### ISSUE TITLE
Emitt events to Vue root instead locally

### ISSUE THREAD

**Issue by kamsi** [formio/vue-formio#14]
@randallknutson I have a suggestion (I can make a PR if you consider it worthwhile).

I think that it would be better to emit events to the Vue root instead in scope of local component like it is done now (here: https://github.com/formio/vue-formio/blob/v3.0.0/src/components/Form.ts#L131 and here: https://github.com/formio/vue-formio/blob/v3.0.0/src/components/Form.ts#L135 ). It takes away one issue I had with setting up listeners. Because Formio loads itself asynchronously I need to make sure that my refs are already available, sadly I had problems to grab my refs in "mounted" lifecycle hook, which made it problematic to attach my listeners. Now, if the event would have been emitted to the Vue root I could setup my listeners in whatever lifecycle hook I want and execute some callbacks involving having refs safely.

**Comment by kamsi** [comment]
@randallknutson 
Actually the one on instance should be left for compatibility, I would only add one on vue root. If I had permissions I would open the PR...

**Comment by airarrazaval** [comment]
The problem I see defining it at the root level is when you have multiple forms instances. 

What you should do is use existing events (as for example `render`) and create your logic from there.

For example:

`@/components/FormioForm.vue`
```vue
<template>
  <formio src="https://examples.form.io/example" @render="onFormRender"></formio>
</template>

<script>
import { Form } from 'vue-formio';

export default {
  name: 'formio-form',
  components: { formio: Form },
  methods: {
    onFormRender() {
      this.$root.$emit('my-root-event');
    },
  }
};
</script>
```

Now instead of using the vanilla `vue-formio` Form component you use yours.

**Comment by kamsi** [comment]
@airarrazaval as you can see in my PR I actually changed my mind a bit and added the root level emit alongside component level emit. This way you can choose if you listen directly on component or on the $root.
So you can listen to any event emitted by any formio instance embedded in your component, no matter how deeply nested inside your component it is.
Still, thanks for giving me another idea on how to attach listener in a way that it ensures having reference to formio via $refs.
Anyway I guess I can close this one as I managed without it after all.
