### ISSUE TITLE
Npm package not updated

### ISSUE THREAD

**Issue by cabrerabywaters** [formio/vue-formio#17]
Hello @randallknutson!
I just tried updating the package to get the language functionality, but it seems that the npm package does not have the latest version, is it possible for you to compile and publish the current vue-formio version?

Best Ignacio

**Comment by cabrerabywaters** [comment]
Hello @randallknutson, @travist.
Is someone maintaining this repo?

**Comment by randallknutson** [comment]
Hi @cabrerabywaters,

We are still maintaining this. We don't typically do a new release every time we update formio.js. It should install the latest version of formio.js if you reinstall. If not you can manually pick your version of formio.js by just installing it with npm. If there is some reason this doesn't work let us know and we can fix it.

**Comment by airarrazaval** [comment]
@randallknutson, @travist I have verified and in fact the NPM package is not updated.  It shows v 3.0.1, but it did not catch the latest changes.  You can try looking at the [Form.d.ts](https://unpkg.com/vue-formio@latest/lib/components/Form.d.ts) un unpkg.  As you see, the language property (included in the latest pull request) is not defined.

`https://unpkg.com/vue-formio@latest/lib/components/Form.d.ts`
```ts
import Vue from 'vue';
import Formio from 'formiojs/Formio';
export default class  extends Vue {
    formio?: Formio;
    src?: string;
    url?: string;
    form?: object;
    submission?: object;
    options?: object;
    srcChange(value: string): void;
    urlChange(value: string): void;
    formChange(value: object): void;
    submissionhange(value: object): void;
    mounted(): void;
    destroyed(): void;
    initializeForm(): Promise<any>;
    setupForm(): void;
    render(createElement: any): any;
}
```

When in reallity it should be:

```ts
import Vue from 'vue';
import Formio from 'formiojs/Formio';
export default class  extends Vue {
    formio?: Formio;
    src?: string;
    url?: string;
    form?: object;
    submission?: object;
    language?: string;
    options?: object;
    srcChange(value: string): void;
    urlChange(value: string): void;
    formChange(value: object): void;
    submissionChange(value: object): void;
    languageChange(value: string): void;
    mounted(): void;
    destroyed(): void;
    initializeForm(): Promise<any>;
    setupForm(): void;
    render(createElement: any): any;
}
```

You may also check in [Form.js](https://unpkg.com/vue-formio@latest/lib/components/Form.js) and you will see that there is no definition of the `language` property.

**Comment by randallknutson** [comment]
I published a new version which should contain the updated files. Please check it out.

**Comment by airarrazaval** [comment]
@randallknutson the issue has been  in 3.0.2.  Thank you very much.

**Comment by travist** [comment]
@airarrazaval do you mean the issue still exists with 3.0.2?

**Comment by cabrerabywaters** [comment]
All good in version 3.0.2 ;), seems that Alfredo forgot the word "fixed"

**Comment by goatandsheep** [comment]
can we close this ticket?

**Comment by travist** [comment]
Yes. Thanks @goatandsheep
