### ISSUE TITLE
Formio and vue js in js format not typeScript !!

### ISSUE THREAD

**Issue by amirmf** [formio/vue-formio#2]
Is it possible to publish this version in javaScript format !?
And also when the stable version will be released!?

**Comment by CompTrain** [comment]
@amirmf If you install the package via npm, you will notice that the files are no longer in Typescript and are just pure Javascript.  Hope this helps!

**Comment by randallknutson** [comment]
CompTrain is correct. You are not required to use Typescript if you install it from npm/yarn. Stable version is now released.
