### ISSUE TITLE
Add 'Basic Usage' part to README

### ISSUE THREAD

**Issue by CompTrain** [formio/vue-formio#3]
I'd like to recommend that you guys add a `Basic Usage` section to the README to help folks.

This is my recommendation:

------------------

## Basic Usage

HTML inside of Vue template file:

```
<template>
  <div id="app">
    <formio src="" url="" form="" submission="" options="" v-on:submit=""></formio>
  </div>
</template>
```

Javascript inside of Vue template file.

```
<script>

  import FormIo from 'vue-formio';

  export default {

      name: 'app',
      components: { FormIo },
  }
</script>
```

**Comment by randallknutson** [comment]
Done a while ago.
