### ISSUE TITLE
Form Rendering Error (missing components)

### ISSUE THREAD

**Issue by airarrazaval** [formio/vue-formio#4]
I am trying to render https://examples.form.io/example using **vue-formio** as per documentation. 

Received the following error when rendered:

Unknown component: content
Unknown component: columns
Unknown component: survey
Unknown component: signature
Unknown component: button

Is this library incomplete, or missing some configurations?

```js
import { Form } from 'vue-formio';

export default {
  name: 'App',
  components: {
    formio: Form,
  }
}
```

```html
<formio src="https://examples.form.io/example" ></formio>
```

**Comment by randallknutson** [comment]
This is some strangeness that occurs from the way the formio.js library is structured (We're working on it). Components have to be manually loaded into the form and if not, you'll get something that looks like what you see. 

I'm not sure why you were seeing it as we've got the code in place. You can see it here: https://github.com/formio/vue-formio/blob/master/src/components/Form.ts#L4-L6

Are you doing anything different in how you load formio.js?
