### ISSUE TITLE
Uncaught TypeError: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by lailapfit** [formio/vue-formio#53]
I am currently using "vue-formio": "^4.0.7" without Typescript and coming across the 'namespace' error. 
I was able to fix the issue by editing Form.js line 144

from 
`var namespace = _this.options.namespace || 'formio';`

to
`var namespace = _this.hasOwnProperty('options') ? _this.options.namespace : 'formio';`

When I pushed the code into production via vercel it is retrieving the current lib, is there a way to extend the Form.js setupForm function with my changes?

**Comment by lailapfit** [comment]
I was able to add my changes into my production build by using this [fix](https://stackoverflow.com/questions/13300137/how-to-edit-a-node-module-installed-via-npm) via [patch-package](https://www.npmjs.com/package/patch-package)!

**Comment by fermuch** [comment]
I've just found this same error. Can we reopen this issue, as it is not fixed yet?
