### ISSUE TITLE
Panel Component not rendering title

### ISSUE THREAD

**Issue by airarrazaval** [formio/vue-formio#7]
Formio Panel Component do not render its title.  The component renders the component as the following bootstrap component:

```html
<div class="card border-{{ theme }} panel panel-{{ theme }}">
    <div class="card-body panel-body">
        ...
    </div>
</div>
```

thus, not rendering the component's legend property.  

It should render the following:

```html
<div class="card border-{{ theme }} panel panel-{{ theme }}">
    <div class="card-header panel-heading bg-{{ theme }} text-white">
        {{ title }}
    </div>
    <div class="card-body panel-body">
        ...
    </div>
</div>
```

**Comment by randallknutson** [comment]
Do you have title in your component definition? It should render just fine if so. This is where the title gets added: https://github.com/formio/formio.js/blob/master/src/components/panel/Panel.js#L68
